service: afterlife-financials-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  app:
    handler: lambda.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/aws-sdk/**
